#shaders/shaders.properties
#Minecraft Settings
oldLighting=false
underwaterOverlay = false
sun=true
moon=true

screen=[SHADOWS] [TERRAIN] [WATER] [POST_EFFECTS]

screen.SHADOWS = SHADOW_MAP_RESOLUTION SHDAOW_DISTANCE SUN_PATH_ROTATION
screen.TERRAIN = WAVY_STUFF
screen.WATER = UNDERWATERFIX
screen.POST_EFFECTS = VIGNETTE

sliders = SHADOW_MAP_RESOLUTION SHDAOW_DISTANCE SUN_PATH_ROTATION
